# Generated by Django 5.0.3 on 2024-06-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euro2024app', '0001_initial'),
    ]

    operations = [
    ]
